# Generated by Django 3.0.8 on 2020-07-10 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted', to='auctions.Listing')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlistings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
