# Generated by Django 3.0.8 on 2020-07-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
